[package]
edition = '2021'
keywords = ['git-remote', 'git', 'gosh']
name = 'git-remote-gosh'
version = '0.1.0'
resolver = "2"

[profile.profiling]
inherits = "release"
debug = 1

[dependencies]
git2 = '^0'
indexmap = '^1'
log = '^0'
log4rs = '^1'
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
base64 = "0.13.0"
base64-serde = "0.6.1"
bytes = "^1"
lazy_static = '^1'
git-traverse = '^0.15.0'
git-revision = '^0'
git-diff = '^0.16.0'
git-object = "^0.19.0"
git-hash = "^0.9.3"
git-odb = "^0.30.0"
git-repository = "^0.19.0"
shellexpand = "2.1.0"
lru = "0.7.7"
primitive-types = "0.11.1"
tracing-futures = { version = "0.2.5", default-features = true }
tracing-log = "0.1.3"
data-contract-macro-derive = { path = "crates/data-contract-macro-derive" }
diffy = { path = "crates/diffy-patched" }
hex = "0.4"
futures = "^0.3"

[dependencies.tracing]
features = ['log', 'attributes', 'std']
version = "^0.1.35"

[dependencies.reqwest]
features = ['multipart', 'stream', 'json']
version = '^0.11.11'

[dependencies.tokio]
features = ['full']
version = '1.19.2'

[dependencies.ton_client]
git = 'https://github.com/tonlabs/ever-sdk.git'
tag = '1.35.1'
package = 'ton_client'

[dependencies.ton_sdk]
git = 'https://github.com/tonlabs/ever-sdk.git'
tag = '1.35.1'
package = 'ton_sdk'

[dependencies.zstd]
default-features = false
version = '^0'

[patch.crates-io]
"tokio" = { git = "https://github.com/tokio-rs/tokio", tag = "tokio-1.19.2" }

[lib]
name = 'git_remote_gosh'
path = 'src/lib.rs'

[[bin]]
name = "git-remote-gosh"
path = "src/main.rs"

[[bin]]
name = "git-remote-gosh-vscode-debug"
path = "src/vscode-debug.rs"
